FROM maven:3.8.8-eclipse-temurin-21-alpine AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk-21.0.1
COPY --from=build /target/springsilver-0.0.1-SNAPSHOT.jar springsilver.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","springsilver.jar"]